### ISSUE TITLE
Make the NewRESTFullAPIWatcherStore client resilient and reliable on full resync

### ISSUE THREAD

**Issue by machi1990** [openshift-online/maestro#131]
This is to track https://github.com/openshift-online/maestro/issues/104#issuecomment-2167777162 
The client I was using is similar to https://github.com/openshift-online/maestro/blob/main/examples/manifestworkclient/client-a/main.go 

and I toggled `WithResyncEnabled(true)` to `true`
/cc @skeeey

**Comment by skeeey** [comment]
The resync only for the client that has the local cache, in our case, the client does not have the local cache, so we should not enable the resync

I enhanced the RESTFulAPIWatcherStore in #133,  it will list works from maestro server when a watcher is required, so that we have a full sync when a client creates

**Comment by clyang82** [comment]
The issue was fixed. free feel to reopen it if you have any questions. Thanks.
